keystore:
  password: "![oglK0vv+lop10jrBthtdrQ==]"
  keyPassword: "![oglK0vv+lop10jrBthtdrQ==]"
  
client:
  client_id: "![hB0TmUm77xGHQVg2p1XKzd+h8UMy77XmzpnHvP9NkCxOaATtxNa1NTYVQbjBApWB]"
  client_secret: "![B9eVG6HauwnqLDh2QsAIuZ+uLNaDhUrp11pXsK9sTGKcaL9rpseJjvEP3EcScKqW]"