{
  "headers": {
    "host": "localhost:8082",
    "connection": "keep-alive",
    "content-length": "438",
    "sec-ch-ua": "\"Microsoft Edge\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"",
    "sec-ch-ua-platform": "\"Windows\"",
    "content-type": "application/json",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0",
    "client_secret": "224b5755312244F1B1db26032870f027",
    "client_id": "a506f44db6264db1a22f13e20c825921",
    "accept": "*/*",
    "origin": "https://localhost:8082",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "https://localhost:8082/console/",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "en-US,en;q=0.9,en-IN;q=0.8"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/accounts",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/accounts",
  "listenerPath": "/api/*",
  "relativePath": "/api/accounts",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/accounts",
  "rawRequestPath": "/api/accounts",
  "remoteAddress": "/127.0.0.1:59817",
  "requestPath": "/api/accounts"
}