app:
  name: "accounts-papi"
  version: "v1"
  appId: "19397678"

https:  
  host: "0.0.0.0"
  port: "8082"
  private:   
    port: "8092"
  path: "/api/*"
  timeOut: "30000"
  idleTimeOut: "40000"

keystore:
  path: "keystore.jks"
  alias: "mule-server"

firstCountrySapiRequest:
  host: "first-country-lookup-sapi.us-e2.cloudhub.io"
  port: ""
  path: "/api/countries/{iso_code}"
  idleTimeout: "30000"
  responseTimeout: "60000"

accountSapiRequest:
  host: "accounts-sfdc-sapi1.us-e2.cloudhub.io"
  port: ""
  putPath: "/api/accounts/{account_id}"
  postPath: "/api/accounts"
  idleTimeout: "30000"
  responseTimeout: "60000"
